### PR TITLE
Nuvoton NUC123SD4AN0 MCU port, ready for Ducky One 2 Mini keyboard

### PR DESCRIPTION
**Pull request by GitWellBack**
This is the MCU port for the Ducky One 2 mini. Drivers and requisite CMSIS files included. Original manufacturer copyright notices have naturally been kept for files directly from there.

Drivers and keyboard code within the main QMK repo will need these merged first.

### CODE REVIEW

**Comment by drashna** [comment]
@qmk/collaborators

**Comment by drashna** [comment]
@GitWellBack it may be a good idea to merge this upstream, as well.  To the chibiOS repo.  That way, if it gets merged there, it's easier to handle here.  Also, it gets merged upstream and more projects can use that hardware too! 

(also, I have a PR to update from upstream, so it would, in theory be easier to maintain long term)

**Comment by skydevht** [comment]
Patch to getting it to compile
https://pastebin.com/23EArVcY

**Comment by melvyn2** [comment]
Seems like the Das Keyboard 4 [also uses the NUC123SD4AN0](https://www.anandtech.com/show/10865/das-keyboard-4-professional-prime-13/2):
image

**Comment by elfmimi** [comment]
I think this can be closed for https://github.com/qmk/qmk_firmware/pull/11112
@tzarc

**Comment by tzarc** [comment]
Yep!

**Pull request closed without merging**
